### PR TITLE
chore: update sockaddr to fix build

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
Test failure: https://github.com/libp2p/go-netroute/issues/8.

Merging because it's not actually related to this patch.

**Comment by willscott** [comment]
the linux impl is failing to instantiate on circle:
```
netroute_test.go:12: out of order iface 1 = {6436 1500 eth0 02:42:ac:1c:00:03 up|broadcast|multicast}
```
it looks like in circle the call to `net.Interfaces()` is doing something fun in terms of containerization.

**Comment by willscott** [comment]
that code is unchanged from what's in gopacket. It's probably something to fail softer on in order to be happier running in situations without full access to the routing table/interfaces on the machine.

**Comment by Stebalien** [comment]
I think we need to relax the restriction on all distros. Links may be in-order, but you can definitely delete links.

**Pull request merged**
