### PR TITLE
Using syscall.RtMsg on Linux

### PR DESCRIPTION
**Pull request by 7sunarni**
I think we don't need to define `struct routeInfoInMemory` because there is already defined struct sycall.RtMsg in [Golang standard library](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_amd64.go)

### CODE REVIEW

**Comment by 7sunarni** [comment]
@willscott

**Comment by willscott** [comment]
I think this would mean the library couldn't be used on arm devices, right? - I see `RtMsg` in the [arm64](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_arm64.go#L470) types, but it isn't there for the [arm](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_arm.go) definitions that would be used for e.g. older raspberry pi's / other armv6/armv7 chips.

I appreciate the simplification - are there other benefits to consider in whether it's worth using the partial upstream definition?

**Comment by 7sunarni** [comment]
> I think this would mean the library couldn't be used on arm devices, right? - I see `RtMsg` in the [arm64](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_arm64.go#L470) types, but it isn't there for the [arm](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_arm.go) definitions that would be used for e.g. older raspberry pi's / other armv6/armv7 chips.

I think you may miss something. There is also `RtMsg` definition in [arm](https://github.com/golang/go/blob/go1.20.10/src/syscall/ztypes_linux_arm.go#L469). So i think it could run in other arm chips.

> are there other benefits to consider in whether it's worth using the partial upstream definition?

Temporary no.

**Comment by willscott** [comment]
you're right! my search missed the arm one. this seems unobjectionable 👍

**Pull request merged**
